### PR TITLE
Fix build error introduced by merge conflict.

### PR DESCRIPTION
**Pull request by abhijit-mahajani-imgtec**
also fix typo in lwm2m-client-ipso-power.c

Signed-off-by: Abhijit Mahajani <Abhijit.Mahajani@imgtec.com>

### CODE REVIEW

**Comment by abhijit-mahajani-imgtec** [comment]
test with jenkins - dev

**Comment by nikhil-zinjurde-imgtec** [comment]
test with jenkins - dev

**Comment by nikhil-zinjurde-imgtec** [comment]
retest this please

**Comment by nikhil-zinjurde-imgtec** [comment]
retest this please

**Pull request merged**
